# Generated by Django 3.0.1 on 2021-08-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_translations'),
    ]

    operations = [
    ]
